@baseUrl = http://localhost:3333
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODkzYTc5My0xODA3LTRjZWMtODcyMi04NzFlOWIzODViOWEiLCJpYXQiOjE3MzEwMTQ5MzcsImV4cCI6MTczMTEwMTMzN30.jJDQfxhnNQEd7KCNeiaFcnjZRtmBW32KG4-6c80zOLb9NWcKvcWa2cgt7Eab5aGhbARtcX9LGoVld_IKfX8USVTJA6S5e2RC5s2cG_lr8dBypLcB5jaH9pYOR8ONBKc3tB2AMAHH5h0iIUDqy66iDWQhe7eFhGy05JUONzrjaZNVzB4QLCejVu1NQGuX75R8-ppuICzoHxU_Apm55lE_5IvONk7Gs-DvnTWLhbWMUWULtEXDT7gsg48enGXrtaw4V2Zgpxs4iB_Qivl1P2amUfiJlL0lP-3WU5m45jW2kGcRK_dpu9m7bXcUXdUcLgEmFRwzbyp3FYqgiI19yMxtjw

# @name create_recipient_account
POST {{baseUrl}}/recipients
Content-Type: application/json

{
  "name": "João Silva",
  "cpf": "12345678900",
  "email": "joao.silva@example.com",
  "password": "senhaSegura123",
  "phone": "+5511998765432"
}

###

# @name authenticate-recipient
POST {{baseUrl}}/authenticate-recipient
Content-Type: application/json

{
  "cpf": "12345678900",
  "password": "senhaSegura123"
}

###

### Exemplo de Uso do Token em uma Requisição Autenticada
# @name create_address
POST {{baseUrl}}/addresses
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "street": "123 Example Street",
  "number": "456",
  "zipcode": "12345-678",
  "city": "Example City",
  "state": "EX",
  "complement": "Apt 789",
  "neighborhood": "Example Neighborhood",
  "latitude": -23.55052,
  "longitude": -46.633308
}

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "addressId": "some-address-id",
  "title": "Order Title",
  "content": "Order Content",
  "status": "pending",
  "isRemovable": true,
  "paymentMethod": "credit_card",
  "deliveryLatitude": -23.55052,
  "deliveryLongitude": -46.633308,
  "shipping": 15.0
}

###

# @name delete_delivery_man
DELETE {{baseUrl}}/delivery-man
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
 "password":"senhaSegura123"
}