@baseUrl = http://localhost:3333
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODkzYTc5My0xODA3LTRjZWMtODcyMi04NzFlOWIzODViOWEiLCJpYXQiOjE3MzA5OTQwOTQsImV4cCI6MTczMTA4MDQ5NH0.j4ghN9wCbtUHxJ6FJLqIx9ysDWqgl3aK-uVgTJFPBGGVFk38L4_wnMWURik8jADev6rGe5kaHvRukMgl4g5yIUs6CDFNQumgQ6i3AKybTiCL9mk0cOvlI0pKv5yVoSBIcgkoZZy9I1Z8Gu6rVLg5d3f08mSXxgrDdXfMCPihHVHVhIKT6ICMrGGlYOn9k_hVfXJ8YgiHfzAU91IZ-Lpf_c2KYcHy9ngF7dTSeSNCkHW_h8FKFeDP1JwpU1IDbntWEg3C-Tsl_Ds3DGsaetgehFvQRWtC1QVNaQrbpmT2IOgW4DmD0Yv-DHEmYLTe-pN-ilon_bZBiTxHrh5gofFQqA

# @name create_recipient_account
POST {{baseUrl}}/recipients
Content-Type: application/json

{
  "name": "João Silva",
  "cpf": "12345678900",
  "email": "joao.silva@example.com",
  "password": "senhaSegura123",
  "phone": "+5511998765432"
}

###

# @name authenticate-recipient
POST {{baseUrl}}/authenticate-recipient
Content-Type: application/json

{
  "cpf": "12345678900",
  "password": "senhaSegura123"
}

###

### Exemplo de Uso do Token em uma Requisição Autenticada
# @name create_address
POST {{baseUrl}}/addresses
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "street": "123 Example Street",
  "number": "456",
  "zipcode": "12345-678",
  "city": "Example City",
  "state": "EX",
  "complement": "Apt 789",
  "neighborhood": "Example Neighborhood",
  "latitude": -23.55052,
  "longitude": -46.633308
}

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "addressId": "some-address-id",
  "title": "Order Title",
  "content": "Order Content",
  "status": "pending",
  "isRemovable": true,
  "paymentMethod": "credit_card",
  "deliveryLatitude": -23.55052,
  "deliveryLongitude": -46.633308,
  "shipping": 15.0
}
