@baseUrl = http://localhost:3333
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODkzYTc5My0xODA3LTRjZWMtODcyMi04NzFlOWIzODViOWEiLCJpYXQiOjE3MzA5NDUzOTF9.gt5bgRbOtZOjA4sCpH011conaX3NlM0m_z8Zm9SMBPy8qQidMbb3yG_CPLeqXChZ7kxNYu3VxbCAwD-wQh7VljK44EDiTC5tddFRitS05ndqAIrVL3xB_A8VyeuTbxZ_7YW02lqfI_PaPvzPikcdNuGQqxBON2RbaKhEhEat5ip0xTtxtYLKkTz6Zdrol6d6jKGc-ZYi7dFlXICDxV1ZTy2uupRsHAuxrf8o3YUgBauF6O9QvHA33KstzkKiM5dQlTMeR84vGJVTpiWU5cAeGMH_rMEf4WAfwu7du1QS-DWHsMLvfpeQ8JRz0tCw0-8IPqFqFr6cYDpmkTqZq8-tqw

# @name create_recipient_account
POST {{baseUrl}}/recipients
Content-Type: application/json

{
  "name": "João Silva",
  "cpf": "12345678900",
  "email": "joao.silva@example.com",
  "password": "senhaSegura123",
  "phone": "+5511998765432"
}

###

# @name authenticate-recipient
POST {{baseUrl}}/authenticate-recipient
Content-Type: application/json

{
  "cpf": "12345678900",
  "password": "senhaSegura123"
}

###

### Exemplo de Uso do Token em uma Requisição Autenticada
# @name create_address
POST {{baseUrl}}/addresses
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "street": "123 Example Street",
  "number": "456",
  "zipcode": "12345-678",
  "city": "Example City",
  "state": "EX",
  "complement": "Apt 789",
  "neighborhood": "Example Neighborhood",
  "latitude": -23.55052,
  "longitude": -46.633308
}
