version: '3.8'

services:
  postgres:
    container_name: fest-feet
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fest-feet-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres